### ISSUE TITLE
Broken links on the Workshop Homepage

### ISSUE THREAD

**Issue by smarkham11037** [cms-opendata-workshop/2022-08-01-cms-open-data-workshop#2]
Hello! I have encountered an issue on the homepage for the 2022 workshop (https://cms-opendata-workshop.github.io/2022-08-01-cms-open-data-workshop/) regarding the pre-exercises section.

There are a couple broken links here: 
- "Virtual Machine" 
- "C++ and ROOT basics"
- "Intro to physics objects"
- "CMSSW Fundamentals"
- "Trigger essentials"

**Comment by caredg** [comment]
[e17e0a1](https://github.com/cms-opendata-workshop/2022-08-01-cms-open-data-workshop/commit/e17e0a1d5e435c3e6a86855fe2bea0b10250a929) closes #2
